"""
downsample_full_duration_and_merge_graphite.py
"""
import logging

# @added 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
import requests

from msgpack import Unpacker

# @modified 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
# Added HORIZON_SHARDS and SKYLINE_URL
from settings import FULL_NAMESPACE, HORIZON_SHARDS, SKYLINE_URL

from skyline_functions import nonNegativeDerivative, sort_timeseries
from functions.timeseries.determine_data_frequency import determine_data_frequency
from functions.timeseries.downsample import downsample_timeseries
# @added 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
from functions.cluster.is_shard_metric import is_shard_metric
# @added 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
from functions.cluster.shard_host import shard_host

# @added 20240125 - Task #5178: Build and test skyline v4.1.0
try:
    from settings import MIRAGE_ANALYSIS_RESOLUTION
except:
    MIRAGE_ANALYSIS_RESOLUTION = 0

skyline_app = 'mirage'
skyline_app_logger = '%sLog' % skyline_app
logger = logging.getLogger(skyline_app_logger)


# @added 20220414 - Feature #3866: MIRAGE_ENABLE_HIGH_RESOLUTION_ANALYSIS
#                   Task #3868: POC MIRAGE_ENABLE_HIGH_RESOLUTION_ANALYSIS
# To overcome the Graphite unfilled last bucket problem, the FULL_DURATION
# data is downsampled using the Pandas origin='end' backwards resample
# method and then aligning to the resolution and this data replaces the
# FULL_DURATION period in the Graphite timeseries data for analysis only.
# This solves the problem of false positive alerts being generated by
# unfilled buckets where the data in the bucket would 'normalise' over
# the duration of the bucket.  However often times occur where the
# bucket data only has one or two very high or very low values and then
# the average for that unfilled bucket is skewed, causing an outlier.
# When the the rest of the bucket is filled the outlier is flattened.
# This preprocessing method resolves that issue and removes any
# requirement for extending the Graphite first retention period to a
# value > 7days, which resolves this issue but creates an issue in the
# Ionosphere context where features extraction takes a long time and is
# not suitable for high production workload.  Thanks to Pandas for
# introducing backswards resampling in version 1.3.
# TODO, instead of doing this every time.... ONLY do it if the Graphite
# data pings as anomalous .... hmmm
def downsample_full_duration_and_merge_graphite(self, metric, timeseries, known_derivative_metric):
    """
    Return the aligned, downsampled timeseries.

    :param self: self object
    :param metric: the metric base_name
    :param timeseries: the timeseries list
    :param known_derivative_metric: whether known_derivative_metric
    :type self: object or None
    :type metric: str
    :type timeseries: list
    :type known_derivative_metric: boolean
    :return: downsampled_timeseries
    :rtype: list

    """

    metric_resolution = 0
    full_duration_resolution = 60  # default to 60
    resampled_aligned_timeseries = []
    downsampled_timeseries = []
    full_duration_timeseries = []
    redis_metric_name = '%s%s' % (FULL_NAMESPACE, str(metric))

    try:
        metric_resolution = determine_data_frequency(skyline_app, timeseries, False)
    except Exception as err:
        logger.error('error :: determine_data_frequency failed for %s - %s' % (
            metric, err))
        metric_resolution = 0
    logger.info('Graphite data resolution is %s seconds with %s data points for %s' % (
        str(metric_resolution), str(len(timeseries)), metric))
    logger.info('Graphite data last data points for %s: %s' % (
        metric, str(timeseries[-3:])))

    # @added 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
    # Determine the shard host to request the Redis data from instead
    # of calling the cluster_data call on all nodes
    use_url = str(SKYLINE_URL)

    # @added 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
    # Added HORIZON_SHARDS
    shard_metric = True
    if HORIZON_SHARDS:
        shard_metric = is_shard_metric(metric)
        # @added 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
        # Determine the shard host to request the Redis data from instead
        # of calling the cluster_data call on all nodes
        if not shard_metric:
            try:
                use_url = shard_host(metric, return_fqdn=True)
            except Exception as err:
                logger.error('error :: shard_host failed with %s, err: %s' % (
                    metric, err))

    if metric_resolution != full_duration_resolution:

        # @added 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
        # Added HORIZON_SHARDS
        if HORIZON_SHARDS:
            if not shard_metric:
                try:
                    # @modified 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
                    # Just query the shard host not the whole cluster
                    #url = '%s/api?metric=%s&cluster_data=true' % (SKYLINE_URL, redis_metric_name)
                    logger.info('getting Redis data for %s from %s' % (
                        metric, use_url))
                    url = '%s/api?metric=%s&cluster_data=false' % (use_url, redis_metric_name)
                    connect_timeout = 5
                    read_timeout = 5
                    use_timeout = (int(connect_timeout), int(read_timeout))
                    r = requests.get(url, timeout=use_timeout)
                    response = r.json()
                    full_duration_timeseries = response['results']
                except Exception as err:
                    url = '%s/api?metric=%s&cluster_data=false' % (use_url, redis_metric_name)
                    logger.error('error :: failed to get full duration timeseries data from Redis via cluster node for %s from %s, err: %s' % (
                        metric, url, err))

                # @modified 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
                # While testing if the Redis time series data is not fetched
                # from the shard_host, make a cluster call
                if not full_duration_timeseries:
                    logger.info('warning :: no Redis data for %s from %s' % (
                        metric, use_url))
                    try:
                        url = '%s/api?metric=%s&cluster_data=true' % (SKYLINE_URL, redis_metric_name)
                        connect_timeout = 5
                        read_timeout = 5
                        use_timeout = (int(connect_timeout), int(read_timeout))
                        r = requests.get(url, timeout=use_timeout)
                        response = r.json()
                        full_duration_timeseries = response['results']
                    except Exception as err:
                        url = '%s/api?metric=%s&cluster_data=true' % (SKYLINE_URL, redis_metric_name)
                        logger.error('error :: failed to get full duration timeseries data from Redis via the cluster_data for %s from %s, err: %s' % (
                        metric, url, err))

        # @modified 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
        # Only try Redis if full_duration_timeseries has not been fetched from
        # another cluster node
        if not full_duration_timeseries and self is not None:
            # Get the Redis FULL_DURATION timeseries data for the metric
            logger.info('downsampling Redis FULL_DURATION data to %s seconds and aligning to replace Graphite FULL_DURATION period for %s' % (
                str(metric_resolution), metric))
            try:
                raw_series = self.redis_conn.get(redis_metric_name)
                unpacker = Unpacker(use_list=False)
                unpacker.feed(raw_series)
                full_duration_timeseries = list(unpacker)
                if full_duration_timeseries:
                    full_duration_timeseries = sort_timeseries(full_duration_timeseries)
                logger.info('got %s data points from Redis FULL_DURATION data for %s to downsample' % (
                    str(len(full_duration_timeseries)), metric))
                logger.info('Redis FULL_DURATION data last data points for %s: %s' % (
                    metric, str(full_duration_timeseries[-6:])))
            except Exception as err:
                logger.error('error :: failed to get full duration timeseries data from Redis for %s - %s' % (
                    metric, err))
    else:
        logger.info('not preprocessing data because metric_resolution is %s seconds for %s' % (
            str(metric_resolution), metric))

    # @added 20240125 - Task #5178: Build and test skyline v4.1.0
    # If the Graphite metric_resolution is less than 600 downsample the Graphite
    # data as well
    use_resolution = int(metric_resolution)
    if MIRAGE_ANALYSIS_RESOLUTION and metric_resolution < MIRAGE_ANALYSIS_RESOLUTION:
        use_resolution = int(MIRAGE_ANALYSIS_RESOLUTION)
        logger.info('downsampling Graphite data for %s with %s data points from %s seconds to %s seconds' % (
            metric, str(len(timeseries)), str(metric_resolution),
            str(use_resolution)))
        method = 'mean'
        try:
            resampled_graphite_timeseries = downsample_timeseries(skyline_app, timeseries, metric_resolution, use_resolution, method, origin='end')
        except Exception as err:
            logger.error('error :: downsample_timeseries failed on timeseries - %s' % err)
        # Remove all nan because they break things
        removed_nans = 0
        if resampled_graphite_timeseries:
            resampled_graphite_timeseries_no_nans = []
            for ts, v in resampled_graphite_timeseries:
                if str(v) == 'nan':
                    removed_nans += 1
                    continue
                resampled_graphite_timeseries_no_nans.append([ts, v])
        if removed_nans:
            logger.info('removed %s nan values from downsampled Graphite data for %s' % (
                str(removed_nans), metric))
            resampled_graphite_timeseries = list(resampled_graphite_timeseries_no_nans)
            del resampled_graphite_timeseries_no_nans
        logger.info('downsampled Graphite data for %s downsampled to %s data points at %s seconds' % (
            metric, str(len(resampled_graphite_timeseries)), str(use_resolution)))
        logger.info('downsampled Graphite data last data points for %s: %s' % (
            metric, str(resampled_graphite_timeseries[-3:])))
        if resampled_graphite_timeseries:
            timeseries = list(resampled_graphite_timeseries)
            del resampled_graphite_timeseries

    # @added 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
    # Added HORIZON_SHARDS
    determined_full_duration_resolution = None
    if HORIZON_SHARDS and self is None:
        if not shard_metric:
            try:
                namespace = metric.split('.')[0]
                # @modified 20250328 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
                # Just query the shard host not the whole cluster.
                # And actually in this instance this cluster node and all
                # cluster nodes should have the metrics_resolutions for each
                # parent namespace.  An external request is not required as each
                # cluster node will have metrics for each parent namespace and
                # their resolutions in Redis so the node can can itself rather
                # than calling the shard_host node as done above.  Further this
                # request must pass cluster_call=true to override a cluster_data
                # call as this metrics_resolutions is one of the methods that
                # forces a cluster_data call, unless cluster_call is set to
                # True.
                #url = '%s/api?metrics_resolutions&namespace=%s&cluster_data=true' % (SKYLINE_URL, namespace)
                url = '%s/api?metrics_resolutions&namespace=%s&cluster_data=false&cluster_call=true' % (use_url, namespace)
                connect_timeout = 5
                read_timeout = 5
                use_timeout = (int(connect_timeout), int(read_timeout))
                r = requests.get(url, timeout=use_timeout)
                response = r.json()
                full_duration_resolution = int(response['data']['resolutions'][metric])
                determined_full_duration_resolution = int(full_duration_resolution)
            except Exception as err:
                url = '%s/api?metrics_resolutions&namespace=%s&cluster_data=false&cluster_call=true' % (use_url, namespace)
                logger.error('error :: failed to get full_duration_resolution from cluster node for %s from %s, err: %s' % (
                    metric, url, err))
                full_duration_resolution = 60

    # @modified 20250327 - Feature #5612: downsample_full_duration_and_merge_graphite - cluster aware
    # Only get if not fetched from the cluster
    if determined_full_duration_resolution is None and self is not None:
        try:
            full_duration_resolution_str = self.redis_conn_decoded.hget('analyzer.metrics_manager.resolutions', metric)
            if full_duration_resolution_str:
                full_duration_resolution = int(float(full_duration_resolution_str))
        except Exception as err:
            logger.error('error :: failed to determine current_resolution from analyzer.metrics_manager.resolutions Redis hash for %s - %s' % (
                metric, err))

    logger.info('Redis FULL_DURATION data resolution is %s seconds for %s' % (
        str(full_duration_resolution), metric))

    if full_duration_timeseries:
        method = 'mean'
        # if known_derivative_metric:
        #    method = 'sum'

        full_duration_timeseries = [[int(t), v] for t, v in full_duration_timeseries]
        try:
            logger.info('downsampling FULL_DURATION data with full_duration_resolution: %s, use_resolution: %s' % (
                str(full_duration_resolution), str(use_resolution)))

            # @modified 20240125 - Task #5178: Build and test skyline v4.1.0
            # resampled_aligned_timeseries = downsample_timeseries(skyline_app, full_duration_timeseries, full_duration_resolution, metric_resolution, method, origin='end')
            resampled_aligned_timeseries = downsample_timeseries(skyline_app, full_duration_timeseries, full_duration_resolution, use_resolution, method, origin='end')
        except Exception as err:
            logger.error('error :: downsample_timeseries failed on full_duration_timeseries - %s' % err)
        logger.info('FULL_DURATION data for %s downsampled to %s data points at %s seconds' % (
            metric, str(len(resampled_aligned_timeseries)), str(use_resolution)))
        logger.info('downsampled FULL_DURATION data last data points for %s: %s' % (
            metric, str(resampled_aligned_timeseries[-3:])))

    # @added 20220506 - Feature #3866: MIRAGE_ENABLE_HIGH_RESOLUTION_ANALYSIS
    #                   Task #3868: POC MIRAGE_ENABLE_HIGH_RESOLUTION_ANALYSIS
    # Remove all nan because they break histogram_bins
    removed_nans = 0
    if resampled_aligned_timeseries:
        resampled_aligned_timeseries_no_nans = []
        for ts, v in resampled_aligned_timeseries:
            if str(v) == 'nan':
                removed_nans += 1
                continue
            resampled_aligned_timeseries_no_nans.append([ts, v])
    if removed_nans:
        logger.info('removed %s nan values from downsampled FULL_DURATION data for %s' % (
            str(removed_nans), metric))
        resampled_aligned_timeseries = list(resampled_aligned_timeseries_no_nans)
        del resampled_aligned_timeseries_no_nans

    # The resampled_aligned_timeseries data must have nonNegativeDerivative
    # applied if it is a derivative_metric
    if resampled_aligned_timeseries and known_derivative_metric:
        logger.info('running nonNegativeDerivative on resampled data %s' % (
            metric))
        try:
            derivative_resampled_aligned_timeseries = nonNegativeDerivative(resampled_aligned_timeseries)
            resampled_aligned_timeseries = derivative_resampled_aligned_timeseries
            logger.info('resampled_aligned_timeseries data last data points for %s (after nonNegativeDerivative): %s' % (
                metric, str(resampled_aligned_timeseries[-6:])))
        except Exception as err:
            logger.error('error :: nonNegativeDerivative failed on resampled_aligned_timeseries for %s - %s' % (
                metric, err))

    if resampled_aligned_timeseries:
        # Replace the period data in the Graphite timeseries with the data
        # in the downsampled timeseries
        logger.info('creating aligned downsampled_timeseries for %s' % metric)
        first_aligned_timestamp = resampled_aligned_timeseries[0][0]
        for ts, v in timeseries:
            if int(ts) < first_aligned_timestamp:
                downsampled_timeseries.append([int(ts), v])
            else:
                break
        downsampled_timeseries = downsampled_timeseries + resampled_aligned_timeseries
        logger.info('created aligned downsampled_timeseries for %s with %s data points' % (
            metric, str(len(downsampled_timeseries))))

    return downsampled_timeseries
