"""
manage_inactive_labelled_metrics_resolution_hashes.py
"""
import logging
from time import time

skyline_app = 'analyzer'
skyline_app_logger = '%sLog' % skyline_app
logger = logging.getLogger(skyline_app_logger)


# @added 20260428 - Feature #5729: metrics_manager - optimise labelled_metrics metric resolution and sparsity hashes
#                   Feature #4792: functions.metrics_manager.manage_inactive_metrics
def manage_inactive_labelled_metrics_resolution_hashes(self):
    """
    A metrics_manager task to clear inactive metrics from the
    labelled_metrics.metric_resolutions and
    labelled_metrics.resolution_sparsity_last_checked Redis hashes on metric ids
    from metrics_manager.inactive_metric_ids.
    Although these hashes are generated by metrics_manager those functions do
    not handled pruning inactive labelled_metrics from the hashes.  This
    function running once every 24 hours is suffice.

    :param self: the self object
    :type self: object
    :return: removed_count
    :rtype: int

    """
    function_str = 'metrics_manager :: manage_inactive_labelled_metrics_resolution_hashes'
    start = time()
    logger.info('%s :: checking for inactive metric ids in labelled_metrics.metric_resolutions and labelled_metrics.resolution_sparsity_last_checked Redis hashes' % function_str)

    inactive_metric_ids_to_remove = []
    hashes = [
        'labelled_metrics.metric_resolutions',
        'labelled_metrics.resolution_sparsity_last_checked',
        'labelled_metrics.data_sparsity',
    ]

    ttl_key_exists = False
    ttl_key = 'metrics_manager.manage_inactive_labelled_metrics_resolution_hashes'
    try:
        ttl_key_exists = self.redis_conn_decoded.get(ttl_key)
    except Exception as err:
        logger.error('%s :: failed to get Redis key: %s, err: %s' % (
            function_str, ttl_key, str(err)))
    if ttl_key_exists:
        logger.info('%s :: TTL key %s exists, nothing to do until %s' % (
            function_str, ttl_key, str(ttl_key_exists)))
        return len(inactive_metric_ids_to_remove)

    labelled_metrics_ids_in_hashes = []
    for key in hashes:
        labelled_metrics_ids_in_hash = []
        try:
            labelled_metrics_ids_in_hash = self.redis_conn_decoded.hkeys(key)
            logger.info('%s :: %s labelled_metrics ids in %s' % (
                function_str, str(len(labelled_metrics_ids_in_hash)), key))
        except Exception as err:
            logger.error('%s :: failed to hdel on %s, err: %s' % (
                function_str, key, str(err)))
        if len(labelled_metrics_ids_in_hash) > 1:
            labelled_metrics_ids_in_hashes = labelled_metrics_ids_in_hashes + labelled_metrics_ids_in_hash

    labelled_metrics_ids_present = list(set(labelled_metrics_ids_in_hashes))
    logger.info('%s :: %s unique labelled_metrics ids in hashes' % (
        function_str, str(len(labelled_metrics_ids_present))))

    inactive_labelled_metrics_ids = []
    key = 'metrics_manager.inactive_metric_ids'
    try:
        inactive_labelled_metrics_ids = self.redis_conn_decoded.smembers(key)
        logger.info('%s :: %s inactive labelled_metrics ids in %s' % (
            function_str, str(len(inactive_labelled_metrics_ids)), key))
    except Exception as err:
        logger.error('%s :: failed to smembers on %s, err: %s' % (
            function_str, key, str(err)))

    inactive_metric_ids_to_remove = []
    try:
        inactive_metric_ids_to_remove = [mid_str for mid_str in labelled_metrics_ids_present if mid_str in inactive_labelled_metrics_ids]
        logger.info('%s :: %s inactive labelled_metrics ids in hashes to remove' % (
            function_str, str(len(inactive_metric_ids_to_remove))))
    except Exception as err:
        logger.error('%s :: comprehension failed to create inactive_metric_ids_to_remove, err: %s' % (
            function_str, str(err)))

    if len(inactive_metric_ids_to_remove) > 0:
        for hash in hashes:
            try:
                removed = self.redis_conn_decoded.hdel(hash, *set(inactive_metric_ids_to_remove))
                logger.info('%s :: called hdel on %s with %s inactive metric ids to remove, %s removed' % (
                    function_str, hash, str(len(inactive_metric_ids_to_remove)),
                    str(removed)))
            except Exception as err:
                logger.error('%s :: failed to hdel on %s, err: %s' % (
                    function_str, hash, str(err)))

    ttl = int(start) + 86400
    try:
        self.redis_conn_decoded.setex(ttl_key, 86400, ttl)
        logger.info('%s :: set TTL key %s to %s for next run.' % (
            function_str, ttl_key, str(ttl)))
    except Exception as err:
        logger.error('%s :: failed to setex Redis key: %s, err: %s' % (
            function_str, ttl_key, str(err)))

    logger.info('%s :: completed in %s seconds' % (
        function_str, str(time() - start)))

    return len(inactive_metric_ids_to_remove)
